#!/bin/bash
#PBS -l select=1:ncpus=4:mem=24gb:ngpus=4:gpu_type=RTX6000
#PBS -lwalltime=04:00:00

module load anaconda3/personal

cd $HOME/gnn-drug-discovery/
source activate gnndd
python model/hyperparameter_tuning.py
